### ISSUE TITLE
[1.1a] Game crashing when trying to run -- Exit Code -1

### ISSUE THREAD

**Issue by sukiii111** [JayZX535/iobaddons-mc#1]
[debug.log](https://github.com/JayZX535/iobaddons-mc/files/12386352/debug.log)

Game crashes whenever I try to run with with exit code -1 and rendering overlay

![Screenshot 2023-08-19 175920](https://github.com/JayZX535/iobaddons-mc/assets/135544578/2c923b6d-8bc1-4d06-bd9a-95cbea5709fc)

**Comment by JayZX535** [comment]
Issue resolved by deleting old `iobaddons-common.toml` file.
