### ISSUE TITLE
[1.1a] crashing when selecting cage 

### ISSUE THREAD

**Issue by sukiii111** [JayZX535/iobaddons-mc#2]
[debug.log](https://github.com/JayZX535/iobaddons-mc/files/12386747/debug.log)

**Comment by JayZX535** [comment]
Most likely an issue with Epic Fight and the way it interacts with capabilities.  I recommend contacting them about the issue to see if there is something they need to change on their end, or a known workaround for it (feel free to direct them to this thread if they would like to get in contact).

**Comment by JayZX535** [comment]
Update: Further review finally yielded a solution, this should be fixed for 1.1b!
