### ISSUE TITLE
[1.1a] Game crashes when hovering over flute and cage

### ISSUE THREAD

**Issue by Walatjung** [JayZX535/iobaddons-mc#3]

**Comment by Walatjung** [comment]
[crash-2023-08-21_17.16.08-client.txt](https://github.com/JayZX535/iobaddons-mc/files/12393321/crash-2023-08-21_17.16.08-client.txt)
forgot to add file

**Comment by JayZX535** [comment]
Ah, the crash is related to immersive engineering.  It looks like it's the same issue as Epic Fight, so I'll continue to poke into it, but for now I'll flag the current build as incompatible with IE.

**Comment by JayZX535** [comment]
Should be fixed for 1.1b
