### ISSUE TITLE
[1.1a] Server Crashing when dropping Cage

### ISSUE THREAD

**Issue by BluberryPlay** [JayZX535/iobaddons-mc#4]
Id like to report, dropping the "Dragon Transport Cage" caused a massive lag spike in my server. creating a crash. reading the logs and getting in contact with my server host support team. both came to this conclusion! I thought id report this here, as I'm not too sure where else there is to. I hope this issue can be resolved!

[latest.log](https://github.com/JayZX535/iobaddons-mc/files/12413930/latest.log)

**Comment by JayZX535** [comment]
Thanks for the report!  This appears to be the log from server restart, not from the crash itself, though-- could I take a look at the previous one?  This one doesn't have the crash, that I see.

**Comment by BluberryPlay** [comment]
[2023-08-23-1.log.gz](https://github.com/JayZX535/iobaddons-mc/files/12413951/2023-08-23-1.log.gz)

**Comment by BluberryPlay** [comment]
if you want the full log part ::

java.lang.ClassCastException: class com.iobaddons.iobaddons.item.capability.DragonCageHandler cannot be cast to class ovh.corail.tombstone.api.capability.IProtectedEntity (com.iobaddons.iobaddons.item.capability.DragonCageHandler is in module iobaddons@1.1 of loader 'TRANSFORMER' @661e279d; ovh.corail.tombstone.api.capability.IProtectedEntity is in module tombstone@7.6.5 of loader 'TRANSFORMER' @661e279d)

**Comment by JayZX535** [comment]
Yeah that looks like the issue.  It's the same compatibility error that I've been investigating with other mods.  For now 1.1 seems to be incompatible with Corail Tombstone and many other mods, and I've marked it as such on the download page.  Investigating a global fix...

**Comment by JayZX535** [comment]
Should be fixed for 1.1b
