### ISSUE TITLE
Zippleback unable to be caged

### ISSUE THREAD

**Issue by Artzeayuuh** [JayZX535/iobaddons-mc#6]
Zippleback is uncageable with the gronckle iron cage. Other dragons are all currently working fine :)

![config](https://github.com/JayZX535/iobaddons-mc/assets/144112160/f40e583e-c4c4-4a84-b0a4-eaa6ff376f7d)
![zippleback cage](https://github.com/JayZX535/iobaddons-mc/assets/144112160/1edd425e-4367-4533-9fa4-ea6d7070df5d)

**Comment by JayZX535** [comment]
Ah, thanks for reporting, I've found and fixed the issue.  This will be patched in the next update!

**Comment by Artzeayuuh** [comment]
ohoh very fast :) ty!

**Comment by JayZX535** [comment]
Issue fixed in 1.1d
