### ISSUE TITLE
Spawn config dragons dont seem to be spawning in terralith biomes

### ISSUE THREAD

**Issue by SucksAtstuff** [JayZX535/iobaddons-mc#8]
ive tried to make the dragons spawn in terralith biomes as well as the regular minecraft biomes
i followed what the wiki told me and added all the biomes and their spawn weight and so forth

but they dont spawn in the biomes

iobaddons-spawns.json is attached
[iobaddons-spawns.json](https://github.com/user-attachments/files/17894417/iobaddons-spawns.json)

**Comment by SucksAtstuff** [comment]
so uh the dragons have now started spawning

guess theres no issue anyway

**Comment by JayZX535** [comment]
As the issue appears to have resolved itself I'll go ahead and close this, glad you got it working!
